version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes: github.com/evgfitil/qx

linters-settings:
  errcheck:
    exclude-functions:
      - (io.Closer).Close

issues:
  exclude-use-default: false
