run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gofmt
    - goimports

linters-settings:
  errcheck:
    exclude-functions:
      - (io.Closer).Close
  goimports:
    local-prefixes: github.com/evgfitil/qx

issues:
  exclude-use-default: false
