version: 2

project_name: qx

before:
  hooks:
    - go mod tidy

builds:
  - id: qx
    main: .
    binary: qx
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/evgfitil/qx/cmd.Version={{.Version}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: evgfitil
    name: qx
  draft: false
  prerelease: auto

brews:
  - name: qx
    repository:
      owner: evgfitil
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/evgfitil/qx
    description: Generate shell commands from natural language using LLM
    license: MIT
    install: |
      bin.install "qx"
    test: |
      system "#{bin}/qx", "--help"
    caveats: |
      To enable shell integration (Ctrl+G hotkey), add to your shell config:

        # zsh (~/.zshrc)
        source <(qx --shell-integration zsh)

        # bash (~/.bashrc)
        eval "$(qx --shell-integration bash)"
